name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: gsajdok/p-workflow/.github/workflows/build-react-app.yml@main
  deploy:
    needs: build
    uses: gsajdok/p-workflow/.github/workflows/deploy-frontend.yml@main
    secrets:
      host: ${{ secrets.VPS_HOST }}
      username: ${{ secrets.VPS_USER }}
      key: ${{ secrets.VPS_SSH_KEY }}
      passphrase: ${{ secrets.VPS_PASSPHRASE }}